name: Hello workflow

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      
      - name: Print hello
        run: echo "Hello from GitHUb Actions!"




