name: Hello workflow

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Says hello
        run: echo "Hello from GitHUb Actions!"
      
      - name: Shows current date and time
        run: date

      - name: Shows the name of the branch the triggeres the run
        run: echo ${{ github.ref_name }}

      - name: List the files in repo
        run: ls

      - name: Shows the runner operating system
        run: uname -a

      - name: Test Failure command
        run: exit 1



