name: Hello workflow

on:
  push: [main]

jobs:
  greet:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      
      - name: Print hello
        runs: echo "Hello from GitHUb Actions!"




